# Generated by Django 5.0.7 on 2024-08-28 10:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Expense Type',
                'verbose_name_plural': 'Expense Types',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('total', models.FloatField(default=0, verbose_name='Total')),
                ('paid', models.FloatField(default=0, verbose_name='Paid')),
                ('debt', models.FloatField(default=0, verbose_name='Debt')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created at')),
                ('car_kilometers', models.FloatField(blank=True, null=True, verbose_name='Kilometers')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
            },
        ),
        migrations.CreateModel(
            name='OrderProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('amount', models.FloatField(default=1, verbose_name='Amount')),
                ('discount', models.FloatField(default=0, verbose_name='Discount')),
                ('total', models.FloatField(default=0, verbose_name='Total')),
                ('created_at', models.DateField(auto_now_add=True, null=True, verbose_name='Created at')),
            ],
            options={
                'verbose_name': 'Order Product',
                'verbose_name_plural': 'Order Products',
            },
        ),
        migrations.CreateModel(
            name='OrderService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('part', models.FloatField(default=1, verbose_name='Part')),
                ('total', models.FloatField(default=0, verbose_name='Total')),
                ('created_at', models.DateField(auto_now_add=True, null=True, verbose_name='Created at')),
            ],
            options={
                'verbose_name': 'Order Service',
                'verbose_name_plural': 'Order Services',
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('price', models.FloatField(verbose_name='Price')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.branch', verbose_name='Branch')),
            ],
            options={
                'verbose_name': 'Expense',
                'verbose_name_plural': 'Expenses',
            },
        ),
    ]
