# Generated by Django 5.0.7 on 2024-07-30 17:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mainApp', '0001_initial'),
        ('statsApp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='expensetype',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.branch'),
        ),
        migrations.AddField(
            model_name='expense',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='statsApp.expensetype'),
        ),
        migrations.AddField(
            model_name='order',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.branch'),
        ),
        migrations.AddField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainApp.customer'),
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.branch'),
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='statsApp.order'),
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainApp.product'),
        ),
        migrations.AddField(
            model_name='orderservice',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.branch'),
        ),
        migrations.AddField(
            model_name='orderservice',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='statsApp.order'),
        ),
        migrations.AddField(
            model_name='orderservice',
            name='service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainApp.service'),
        ),
        migrations.AddField(
            model_name='orderservice',
            name='staff',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
