# Generated by Django 5.0.7 on 2024-08-28 10:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mainApp', '0001_initial'),
        ('statsApp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddField(
            model_name='expensetype',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.branch', verbose_name='Branch'),
        ),
        migrations.AddField(
            model_name='expense',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='statsApp.expensetype', verbose_name='Type'),
        ),
        migrations.AddField(
            model_name='order',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.branch', verbose_name='Branch'),
        ),
        migrations.AddField(
            model_name='order',
            name='car',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainApp.car', verbose_name='Car'),
        ),
        migrations.AddField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainApp.customer', verbose_name='Customer'),
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.branch', verbose_name='Branch'),
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='statsApp.order', verbose_name='Order'),
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainApp.product', verbose_name='Product'),
        ),
        migrations.AddField(
            model_name='orderservice',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.branch', verbose_name='Branch'),
        ),
        migrations.AddField(
            model_name='orderservice',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='statsApp.order', verbose_name='Order'),
        ),
        migrations.AddField(
            model_name='orderservice',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainApp.service', verbose_name='Service'),
        ),
        migrations.AddField(
            model_name='orderservice',
            name='staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Staff'),
        ),
    ]
