# Generated by Django 5.0.7 on 2024-08-12 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statsApp', '0003_orderproduct_created_at_orderservice_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderproduct',
            name='created_at',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='orderservice',
            name='created_at',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
