# Generated by Django 5.0.7 on 2024-08-31 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('statsApp', '0004_salary'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderservice',
            old_name='staff',
            new_name='worker',
        ),
    ]
