# Generated by Django 5.0.7 on 2024-08-16 02:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0006_alter_branch_options_alter_car_options_and_more'),
        ('statsApp', '0005_alter_expense_options_alter_expensetype_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='car',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainApp.car', verbose_name='Car'),
        ),
    ]
