# Generated by Django 5.0.7 on 2024-08-31 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statsApp', '0005_rename_staff_orderservice_worker'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='car_kilometers',
        ),
        migrations.AddField(
            model_name='order',
            name='car_kilometers_ev',
            field=models.FloatField(blank=True, null=True, verbose_name='Kilometers EV'),
        ),
        migrations.AddField(
            model_name='order',
            name='car_kilometers_hev',
            field=models.FloatField(blank=True, null=True, verbose_name='Kilometers HEV'),
        ),
        migrations.AddField(
            model_name='order',
            name='car_kilometers_odo',
            field=models.FloatField(blank=True, null=True, verbose_name='Kilometers ODO'),
        ),
    ]
