# Generated by Django 5.0.7 on 2024-08-17 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statsApp', '0006_order_car'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='car_kilometers',
            field=models.FloatField(blank=True, null=True, verbose_name='Kilometers'),
        ),
        migrations.AddField(
            model_name='order',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='orderservice',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
    ]
