# Generated by Django 5.0.7 on 2024-08-28 10:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Address')),
                ('phone_number', models.CharField(blank=True, max_length=13, null=True, verbose_name='Phone number')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
            ],
            options={
                'verbose_name': 'Branch',
                'verbose_name_plural': 'Branchs',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255, verbose_name='First name')),
                ('last_name', models.CharField(max_length=255, verbose_name='Last name')),
                ('phone_number', models.CharField(blank=True, max_length=13, null=True, verbose_name='Phone number')),
                ('phone_number_extra', models.CharField(blank=True, max_length=13, null=True, verbose_name='Phone number')),
                ('passport_serial_numbers', models.CharField(blank=True, max_length=2, null=True, verbose_name='Passport serial numbers')),
                ('passport_serial_letters', models.CharField(blank=True, max_length=7, null=True, verbose_name='Passport serial letters')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Address')),
                ('debt', models.FloatField(default=0, verbose_name='Debt')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.branch', verbose_name='Branch')),
            ],
            options={
                'verbose_name': 'Customer',
                'verbose_name_plural': 'Customers',
            },
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=20, null=True, verbose_name='Code')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('brand', models.CharField(blank=True, max_length=255, null=True, verbose_name='Brand')),
                ('color', models.CharField(blank=True, max_length=50, null=True, verbose_name='Color')),
                ('state_number', models.CharField(blank=True, max_length=10, null=True, verbose_name='State number')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.branch', verbose_name='Branch')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.customer', verbose_name='Customer')),
            ],
            options={
                'verbose_name': 'Car',
                'verbose_name_plural': 'Cars',
            },
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('phone_number', models.CharField(blank=True, max_length=13, null=True, verbose_name='Phone number')),
                ('debt', models.FloatField(default=0, verbose_name='Debt')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.branch', verbose_name='Branch')),
            ],
            options={
                'verbose_name': 'Provider',
                'verbose_name_plural': 'Providers',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=20, null=True, verbose_name='Code')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('amount', models.FloatField(default=0, verbose_name='Amount')),
                ('min_amount', models.FloatField(default=10, verbose_name='Minimum amount')),
                ('unit', models.CharField(blank=True, max_length=50, null=True, verbose_name='Unit')),
                ('import_price', models.FloatField(verbose_name='Import price')),
                ('export_price', models.FloatField(blank=True, null=True, verbose_name='Export price')),
                ('max_discount', models.FloatField(default=0, verbose_name='Max discount')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.branch', verbose_name='Branch')),
                ('provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainApp.provider', verbose_name='Provider')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
        migrations.CreateModel(
            name='ImportProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='Description')),
                ('amount', models.FloatField(default=0, verbose_name='Amount')),
                ('import_price', models.FloatField(blank=True, null=True, verbose_name='Import price')),
                ('total', models.FloatField(default=0, verbose_name='Total')),
                ('debt', models.FloatField(default=0, verbose_name='Debt')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.branch', verbose_name='Branch')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainApp.product', verbose_name='Product')),
                ('provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainApp.provider', verbose_name='Provider')),
            ],
            options={
                'verbose_name': 'Import product',
                'verbose_name_plural': 'Import products',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('price', models.FloatField(verbose_name='Price')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.branch', verbose_name='Branch')),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
            },
        ),
    ]
