# Generated by Django 5.0.7 on 2024-07-26 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='state_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
