# Generated by Django 5.0.7 on 2024-08-31 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='balance',
            field=models.FloatField(default=0, verbose_name='Balance'),
        ),
    ]
