# Generated by Django 5.0.7 on 2024-07-31 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0002_product_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='importproduct',
            name='import_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
