# Generated by Django 5.0.7 on 2024-08-18 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0006_alter_branch_options_alter_car_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='importproduct',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Description'),
        ),
    ]
