# Generated by Django 5.0.7 on 2024-08-31 05:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0002_alter_user_balance_alter_user_branch_alter_user_part_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='part',
            field=models.FloatField(default=1, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Part'),
        ),
    ]
