# Generated by Django 5.0.7 on 2024-08-11 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0005_alter_user_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='part',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='salary',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
